export default function characterModel() {
  return {
    name: '',
    klass: '',
    gender: '',
    availableSkills: [],
    allSkills: [],
    classResources: {},
    tactics: [],
    experience: 0,
    level: 1,
    currentHealth: 100,
    maxHealth: 100,
    currentActionPoints: 3,
    maxActionPoints: 3,
    strength: 10,
    intelligence: 10,
    dexterity: 10,
    perception: 10,
    athletics: 10,
    statGrowth: {
      maxHealth: 0,
      maxActionPoints: 0,
      strength: 0,
      intelligence: 0,
      dexterity: 0,
      perception: 0,
      athletics: 0,
    },
    statusEffects: [],
    equippedWeapons: [],
    // inventory: [],
    maxActiveWeapons: 1,
    companions: [],
    equippedArmour: [],
    baseDamage: 0,
    physicalDefence: 0,
    magicalDefence: 0,
    block: 0,
    evasion: 0,
  };
}

// export { characterModel };
